# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'object-recognizer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for object-recognizer
  pod 'Alamofire', '~> 4.6.0'
  pod 'AlamofireImage', '~> 3.3'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.2'
  pod 'AlamofireObjectMapper', '~> 5.0'
end
